spring:
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
  profiles:
    active: dev
  main:
    banner-mode: console
  datasource:
    url: jdbc:mysql://localhost:${db.port}/pokedex
    username: root
    password: ${DB_PASSWORD}
    jpa:
      hibernate:
        globally_quoted_identifiers: true
        ddl-auto: update
      properties:
        hibernate:
          show_sql: false
          format_sql: false
          use_sql_comments: false


db:
  port: 3306

application:
  jwt_secret: 551EAB3DDF696B8C3D5CCA520CED5980E79CFCEBBD15A42587983E22EBBC4E0B
  jwt_expires_in: 604800000
  title: Pokedex
  version: 1.0.0

server:
  servlet:
    context-path: /pokedex
  forward-headers-strategy: framework

